### ISSUE TITLE
How to get CLion to recognize all the symbols?

### ISSUE THREAD

**Issue by innegatives** [MartinHelmut/cpp-gui-template-sdl2#10]
Thanks for this template, it is really useful.

One issue I'm facing though is getting my IDE to recognize all the symbols. I already tried Neovim but gave up on it and installed CLion to see maybe it is better at that, but it still doesn't recognize SDL stuff.

See the attached screenshot.

Any ideas how to fix this? What is your own setup like?
![2023-06-08-034701_1366x768_scrot](https://github.com/MartinHelmut/cpp-gui-template-sdl2/assets/134976213/bbeabf19-4ce9-464d-b25b-1d2fce9af3dc)

**Comment by MartinHelmut** [comment]
Hey, nice to hear it is of use to you ☺️

I'm using CLion myself without problems (macOS and Windows). It seems like the CMake **configure step** did not execute for you? 🤔 This is where [CMake's FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) will fetch SDL2 and other dependencies ([ref](https://github.com/MartinHelmut/cpp-gui-template-sdl2/blob/main/vendor/CMakeLists.txt#L24)). You can check this by right-clicking on your project folder to _"Reload CMake project"_. The pop-up looks something like this:

<img width="277" alt="project-menu" src="https://github.com/MartinHelmut/cpp-gui-template-sdl2/assets/690957/1b5e9369-7871-414a-aae5-c20acda7af6d">

You can validate this by looking at your CMake console in CLion, it should print the message _"Fetching SDL ..."_ and show no errors. You can also if you like attach the CMake log output from CLion here in this issue.

If this leads to no success, another option is to manually run the configure step via terminal as defined in the [build docs](https://github.com/MartinHelmut/cpp-gui-template-sdl2/blob/main/docs/QuickStart.md#build). The TL;DR is:

```shell
# You don't need to use Ninja
cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -B build/debug
```

And try to build via:

```shell
cmake --build build/debug
```

If non of this helps I can suggest more options that maybe help, but let's try this first 😅
